version: 0.2

phases:
  install:
    commands:
      - echo Installing Meteor
      - curl https://install.meteor.com/ | sh
  pre_build:
    commands:
      - echo Displaying folder structure
      - ls
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - mkdir ../original
      - mv * ../original
      - cd ../original 
      - meteor npm i --production
      - sudo chown -Rh root .meteor/local
      - meteor build ../src --architecture os.linux.x86_64 --allow-superuser --directory
      - cp -R .ebextensions ../src/bundle/
      - cp ./bundle.package.json ../src/bundle/package.json
      - cd ../src/bundle
      - meteor npm i bcrypt -S
      - cd programs/server && npm install --production
      - cd ../..
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -a
artifacts:
  files:
    - 'bundle/**/*'
