version: 0.2

phases:
  install:
    commands:
      - echo Installing Meteor
      - curl https://install.meteor.com/ | sh
  pre_build:
    commands:
      - echo Displaying folder structure
      - ls
  build:
    commands:
      - echo Build started on `date`
      - pwd 
      - meteor npm i --production
      - sudo chown -Rh root .meteor/local
      - mkdir ../BUILD
      - meteor build ../BUILD --architecture os.linux.x86_64 --allow-superuser --directory
      - cp -R ../BUILD/bundle ./
      - cp -R .ebextensions ./bundle/
      - cp ./bundle.package.json ./bundle/package.json
      - cd bundle
      - meteor npm i bcrypt -S
      - cd programs/server && npm install --production
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -a
artifacts:
  files:
    - 'bundle/**/*'
